import dayjs from 'dayjs';

export const PROJECT_DEFAULT_KEY = {
  TODAY: 'today',
  TOMORROW: 'tomorrow',
  THIS_WEEK: 'thisWeek',
  HIGH_PRIORITY: 'highPriority',
  MEDIUM_PRIORITY: 'mediumPriority',
  LOW_PRIORITY: 'lowPriority',
  PLANNED: 'planned',
  BACKLOG: 'backlog',
  COMPLETED: 'completed',
};

export const PROJECT_DEFAULT_DATA = [
  {
    id: PROJECT_DEFAULT_KEY.TODAY,
    name: `Project.${PROJECT_DEFAULT_KEY.TODAY}`,
    icon: '📅',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.TOMORROW,
    name: `Project.${PROJECT_DEFAULT_KEY.TOMORROW}`,
    icon: '⏰',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.THIS_WEEK,
    name: `Project.${PROJECT_DEFAULT_KEY.THIS_WEEK}`,
    icon: '📆',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.HIGH_PRIORITY,
    name: `Project.${PROJECT_DEFAULT_KEY.HIGH_PRIORITY}`,
    icon: '🔴',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.MEDIUM_PRIORITY,
    name: `Project.${PROJECT_DEFAULT_KEY.MEDIUM_PRIORITY}`,
    icon: '🟡',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.LOW_PRIORITY,
    name: `Project.${PROJECT_DEFAULT_KEY.LOW_PRIORITY}`,
    icon: '🟢',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.PLANNED,
    name: `Project.${PROJECT_DEFAULT_KEY.PLANNED}`,
    icon: '📋',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.BACKLOG,
    name: `Project.${PROJECT_DEFAULT_KEY.BACKLOG}`,
    icon: '📚',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
  {
    id: PROJECT_DEFAULT_KEY.COMPLETED,
    name: `Project.${PROJECT_DEFAULT_KEY.COMPLETED}`,
    icon: '✅',
    taskIds: [],
    dueDate: [],
    disabled: true,
    folderId: null,
    createdAt: dayjs().toISOString(),
    modifiedAt: dayjs().toISOString(),
  },
];
